server:
  port: 8082

spring:
    profiles:
        active: dev
#        active: flr
    thymeleaf:
            prefix: classpath:/templates/
            check-template-location: true
            cache: false
            suffix: .html
            encoding: UTF-8
            mode: HTML
            servlet:
              content-type: text/html
    aop:
      auto: true
      proxy-target-class: true

    servlet:
          multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    resources:
      static-locations: classpath:/static/
logging:
  level:
      com.ls.ggtt: debug







